### ISSUE TITLE
@nuxtjs/pwa Now Working in Chrome Lighthouse

### ISSUE THREAD

**Issue by itgelo** [LuXDAmore/nuxt-prune-html#10]

**Comment by LuXDAmore** [comment]
Hi @itgelo 😄 

Can You provide some details about this Issue? 🤔

**Comment by itgelo** [comment]
My nuxt.config.js
```
...
modules: ['@nuxtjs/pwa', '@luxdamore/nuxt-prune-html'],
...
```
I have tried it with or without default module config and the results are the same.
before:
![photo_2020-09-21_16-13-36](https://user-images.githubusercontent.com/15007559/93750322-7d09b880-fc25-11ea-9dc4-99a9e5f9245b.jpg)

after:
![photo_2020-09-21_16-13-44](https://user-images.githubusercontent.com/15007559/93750602-ed183e80-fc25-11ea-80f7-6e91c13d1920.jpg)

**Comment by LuXDAmore** [comment]
I'm using these 2 plugins in a website with over a million url, without issues. 🥇 

Obviously, It could return the same results, depending on how much your site is or is-not performing well.

`nuxt-prune-html` is activated only for bots / Lighthouse (depends on the _user-agent_ and if you are in _production_).


The Performance tab and the PWA tabs are not related, so yes, You have a PWA with 100 score of performances.  😄
