### ISSUE TITLE
web.dev -> Links are not crawlable with nuxt-prune-html

### ISSUE THREAD

**Issue by Aurion72** [LuXDAmore/nuxt-prune-html#11]
When i use the @luxdamore/nuxt-prune-html, https://web.dev/measure/ from Google say "Links are not crawlable" in SEO section with medium impact.

When i remove @luxdamore/nuxt-prune-html and test again, the alert not showing anymore.

How to avoid this message? Does this have an impact on SEO?

**Comment by LuXDAmore** [comment]
Hello @Aurion72 😄 

I'm pretty sure this is not related to the plugin.

[This website](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.fallimenti.it%2F) is online with almost **1 million urls** and is using that plugin. As You can see, without any issues.

But, can You try to reproduce the bug in [codesandbox](https://codesandbox.io/) for example? Or there is a **live demo**?

___

This plugin is intended **to remove Javascript, not the links or the html**.

Have You checked on Google for some advices? (_ex_. [Google support](https://support.google.com/webmasters/answer/9112205))

**Comment by Aurion72** [comment]
@LuXDAmore I found my mistake (was me, my bad), im sorry for the inconvenient. You did a great job with this module, i hope Google won't go against it.
