### ISSUE TITLE
Isn't it black hat?

### ISSUE THREAD

**Issue by CavalcanteLeo** [LuXDAmore/nuxt-prune-html#16]
Is there any risk of using it, like black hat or any other thing?

How does google sees this practice?

Or is it a white hat?

**Comment by LuXDAmore** [comment]
Hi @CavalcanteLeo 😄 

This plugin was firstly published almost 2 years ago..
On a huge website (+1 millions urls) with a wide range of users, we've seen that Google Bot is in love with this plugin! 💯

The site traffic has increased by +50% and the pagerank was increased too, with a spread of the crawler-bot on many other pages.

So, at the moment i'm writing this, **no, it's not a black-hat technique** 🥇 ..
And, as you can see [here](https://www.wordstream.com/black-hat-seo), removing `<script>` is not considered "invalid".


> P.S.: _jtk, due to the BLM movement, we should stop calling it `black hat`._  😄

**Comment by CavalcanteLeo** [comment]
awesome
