### ISSUE TITLE
vue-lazyload not working

### ISSUE THREAD

**Issue by NguyenThanh1995** [LuXDAmore/nuxt-prune-html#19]
Hello, I tested this plugin it's awesome but it doesn't seem to work with vue-lazyload.  How do I make them work at the same time?

**Comment by LuXDAmore** [comment]
Hi @NguyenThanh1995 

Can You provide a reproduction link? What do You intend with "it doesn't seem to work"?

It's compatible but, `vue-lazy-hydration`: _hydrateOnInteraction_, _hydrateWhenIdle_ and _hydrateWhenVisible_ are **javascript client-side code** so they're pruned out.

But I'm not sure a bot need to trigger them, so they are not necessary and it's not a problem 🤷🏻 

Without Javascript You don't have hydration on client-side.

**Comment by NguyenThanh1995** [comment]
Yes. I have decided to get rid of them and no longer need it
