### ISSUE TITLE
Change default string matching for lighthouse

### ISSUE THREAD

**Issue by gangsthub** [LuXDAmore/nuxt-prune-html#2]
Hi!

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

- Following [this list of UAs](https://developers.whatismybrowser.com/useragents/explore/software_name/google-lighthouse/), what if the default string was `lighthouse|google page speed`? Also, it was not directly clear that the `lighthouseUserAgent` was a (string that would compile to a) Regex value.

**Describe the solution you'd like**
- Maybe we could add in the docs that `lighthouseUserAgent` will be converted to a Regex and that, by default, it is [case insensitive](https://hgoebl.github.io/mobile-detect.js/doc/mobile-detect.js.html#line944).

**Comment by LuXDAmore** [comment]
Hi @gangsthub  😄 

This plugin use the Javascript `mobile-detect` library, you can check [HERE](https://hgoebl.github.io/mobile-detect.js/doc/MobileDetect.html#match) for the documentation about the **match** method..

`lighthouseUserAgent` is intended only for lighthouse (due to the fact that it's integrated in Chrome so you can check live for bugs or you can disable it on demand).

If you need to test a new 'userAgent', you can use the property `matchUserAgent: 'String|Pattern'` to handle it..

___

But yes, i think the documentation should be more clear about this feature:

> [ String | RegExp ] the pattern, either as String or RegExp (a string will be converted to a case-insensitive RegExp).

Thank You 🚀, i'm

**Comment by gangsthub** [comment]
BTE, thank you for the library, I'm planning to use it 😉

Did you see the list of UAs that belong to lighthouse that I put in the original comment? That's why I suggested the change; only to target Lighthouse...

And yes, I saw it uses a 3rd party library, that's why I discovered that it is case insensitive by default.

**Comment by LuXDAmore** [comment]
@gangsthub I've seen the list ([here](https://developers.whatismybrowser.com/useragents/parse/682595-google-lighthouse) too), but i think it's a little bit wrong (or outdated), Google is planning to use only Lighthouse (at the moment) to test websites performances, so they're adding the 'Lighthouse' User-Agent to every active system. _(I did some research before publish the plugin, ex. [here](https://github.com/GoogleChrome/lighthouse/issues/7140))_

Ex. [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/), [Measure](https://web.dev/measure/) and [Lighthouse Audit in Chrome](https://developers.google.com/web/tools/lighthouse) are already triggered by the plugin without the needing of change the value.

___

BTW, thank you for your help!  😄 If you have any doubt please don't hesitate to contact me 😎

**Comment by gangsthub** [comment]
> @gangsthub I've seen the list ([here](https://developers.whatismybrowser.com/useragents/parse/682595-google-lighthouse) too), but i think it's a little bit wrong (or outdated), Google is planning to use only Lighthouse (at the moment) to test websites performances, so they're adding the 'Lighthouse' User-Agent to every active system. _(I did some research before publish the plugin, ex. [here](https://github.com/GoogleChrome/lighthouse/issues/7140))_
> 
> Ex. [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/), [Measure](https://web.dev/measure/) and [Lighthouse Audit in Chrome](https://developers.google.com/web/tools/lighthouse) are already triggered by the plugin without the needing of change any value.
> 
> BTW, thank you for your help! 😄 If you have any doubt please don't hesitate to contact me 😎

Oh, that's insightful! Thank you very much for the info!! And for all your work!
