### ISSUE TITLE
Node GC crash when using nuxt:generate 

### ISSUE THREAD

**Issue by sp0ken** [LuXDAmore/nuxt-prune-html#28]
**Describe the bug**
When using the generate command of Nuxt (without static mode set) the generation fails with a Garbage Collection failure.

**To Reproduce**
- Setup a Nuxt Project with the nuxt-prune-html module
- Add a few pages
- Generate the website using `yarn nuxt generate
`
**Expected behavior**
Generation is successful and pruning is applied
 
**Screenshots**
![](https://zupimages.net/up/21/17/mrzr.png)

**Additional context**
I've tested it on my machine and when using Netlify build system.
Node version: 15.14.0

**Comment by LuXDAmore** [comment]
Hello @sp0ken 😄 

This seems a memory leak.. I'm using this module in site with more than one millions urls and there are no memory leaks.

I don't think this is related to the module 🤔 

Could you reproduce the bug?

**Comment by sp0ken** [comment]
Hi @LuXDAmore,

I'll try to provide a reproductible scenario

**Comment by sp0ken** [comment]
Well it seems to be a known issue with Nuxt 2.14+: https://github.com/nuxt/nuxt.js/issues/7855
I've tried to remove as many modules as possible but I'm still getting an Out of memory error.

I'll wait for an upstream fix try again this module again.

**Comment by LuXDAmore** [comment]
Ok, thank You for sharing  😄 

So, I'm gonna close this issue 🌈
