### ISSUE TITLE
It shows blank when I enable nuxt-prune and access it via localhost

### ISSUE THREAD

**Issue by shidcordero** [LuXDAmore/nuxt-prune-html#42]
Here's the config I setup for my nuxt app 

```
export default {
  // Target: https://go.nuxtjs.dev/config-target
  target: 'static',
  ssr: true
}
```

and I add nuxt prune as indicated in the documentation
```
modules: ['@luxdamore/nuxt-prune-html'],

  pruneHtml: {
    enabled: true
  },
```

to test it, I just force enable to true. I use `yarn generate` and `yarn serve` to test it locally, but what it showing is just all white. Did I do something wrong about its implementation?

**Comment by LuXDAmore** [comment]
Hi @shidcordero 

Can you show me a reproduction link?
